// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package songs

// Injectors from wire.go:

func InitializeMovie(line string) Movie {
	song := NewSong(line)
	album := NewAlbum(song)
	movie := NewMovie(album)
	return movie
}
