// Code generated by "stringer -type=Jobs"; DO NOT EDIT.

package codeg

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Director-0]
	_ = x[Producer-1]
	_ = x[Cinematographer-2]
	_ = x[Choreographer-3]
}

const _Jobs_name = "DirectorProducerCinematographerChoreographer"

var _Jobs_index = [...]uint8{0, 8, 16, 31, 44}

func (i Jobs) String() string {
	if i < 0 || i >= Jobs(len(_Jobs_index)-1) {
		return "Jobs(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Jobs_name[_Jobs_index[i]:_Jobs_index[i+1]]
}
